# essilfie.com Jekyll settings


title: "Will Essilfie"
author: "Will Essilfie"
email: "will@essilfie.com"
description: "Product Manager at Teachers Pay Teachers. Previously a Data Scientist, Editor in Chief, and student at Columbia."
baseurl: "" 
url: "https://www.essilfie.com" 
twitter_username: "WillEssilfie"
github_username:  "wessilfie"
via_info: "via New York, NY"
future: false

# Build settings
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /:collection/:title/
  work:
    output: true
    permalink: /:collection/:title/
  posts:
    output: true 
    permalink: /:collection/:title
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
