# essilfie.com Jekyll settings


title: Will Essilfie
email: will@essilfie.com
description: >- # this means to ignore newlines until "baseurl:"
  Product Manager at RangeMe. Previously a Data Scientist, Editor in Chief, and student at Columbia.
baseurl: "" 
url: "https://www.essilfie.com" 
twitter_username: WillEssilfie
github_username:  wessilfie
via_info: via San Francisco

# Build settings
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /:collection/:title/

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
